-- CreateTable
CREATE TABLE `todolist` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `list` VARCHAR(191) NOT NULL,
    `active` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `completed` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
